name: Build and deploy FastAPI app to Azure Web App - rohitfirstapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          cd backend
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Archive backend for deployment
        run: |
          cd backend
          zip -r ../app.zip . -x "venv/*" ".git/*" "__pycache__/*"

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: AZUREAPPSERVICE_CLIENTID_C9BB68E1736E45F9BF2E63A5FD82896B
          tenant-id: AZUREAPPSERVICE_TENANTID_938A9443C0714C3E85975600958A106A
          subscription-id: AZUREAPPSERVICE_SUBSCRIPTIONID_30126F26329C41ADA51B662B45A28FAC

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'rohitfirstapp'
          package: app.zip
